---
- name: Copy web.html
  hosts: target
  vars_files: vars/vars.yml
  
  tasks:
  - name: httpd package is present
    yum:
      name: httpd
      state: latest

  - name: copy web.html
    copy:
      src: "{{ stage1 }}.html"
      dest: /var/www/html/
  
  - name: httpd is started
    service:
      name: httpd
      state: started
  
  - name: check
    ansible.builtin.uri:
      url: http://10.184.0.25
      return_content: true
    register: this
    failed_when: "'appserver' not in this.content"

  - name: debug
    debug:
      var: this
