---
- name: Copy web.html
  hosts: target
  vars_files: vars/vars.yml
  
  tasks:
  - name: httpd package is present
    yum:
      name: httpd
      state: latest
    tags:
      - project1

  - name: copy web.html
    copy:
      src: "{{ stage1 }}.html"
      dest: /var/www/html/
    tags:
      - project1
      - always
  
  - name: httpd is started
    service:
      name: httpd
      state: started
    tags:
      - project1
  
  - name: check
    uri:
      url: http://10.184.0.25
      return_content: true
    register: this
    failed_when: "'webserver' not in this.content"
    tags:
      - project1
      - project2
      - test1

  - name: convert response
    set_fact:
      yaml_string: "{{ this|to_yaml }}"
    tags:
      - test1

  - name: debug
    debug:
      var: yaml_string
    tags:
      - project1
      - project2
      - test1
  
  - name: Create file
    shell: "touch /home/user14/{{ item }}"
    loop:
      - file1
      - file2
      - file3
      - file4
      - file5
    tags:
      - project2

  - name: Echo file
    shell: "echo {{ item }}"
    loop:
      - "one"
      - "two"
    register: echo
    tags:
      - project2

  - name: Debug
    debug:
      var: echo
    tags:
      - project1
      - project2
