---
- name: Copy web.html
  hosts: target
  vars_files: vars/vars.yml
  
  tasks:
  - name: httpd package is present
    yum:
      name: httpd
      state: latest

  - name: copy web.html
    template:
      src: "files/{{ stage1 }}.html"
      dest: /var/www/html/index.html
    notify:
      - Restart httpd
  
  - name: httpd is started
    service:
      name: httpd
      state: started
  
  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
